/*
  config.h
  Author: Trevor Stanhope
  Date: 2013-05-14
  Summary: Configuration Library for MR14
*/

/*********** INPUT/OUTPUT ***********/
/* --- PWM PINS --- */
// PWM 1: SENSORS
#define SENSOR_WHEEL_PIN 2
#define SENSOR_FUEL_PIN 3
#define SENSOR_ENGINE_PIN 4
#define ACTUATOR_FAULT_PIN 6
#define MOTOR_FAULT_PIN 12

/* --- COMMUNICATION PINS --- */
// COMMUNICATION 1: RFID STEERING AND LCD
#define RFID_TX_PIN 16
#define RFID_RX_PIN 17
#define STEERING_A_PIN 18 
#define STEERING_B_PIN 19
#define LCD_SDA_PIN 20
#define LCD_SCL_PIN 21

/* --- START DIGITAL PINS --- */
// DIGITAL 1: KILL, TRIGGER AND LOCK SWITCHES
#define KILL_BUTTON_PIN 22
#define KILL_HITCH_PIN 24
#define KILL_SEAT_PIN 26
#define LOCK_LEFTBRAKE_PIN 28
#define LOCK_RIGHTBRAKE_PIN 30
#define LIMIT_BALLAST_FAR_PIN 32
#define LIMIT_BALLAST_NEAR_PIN 34
#define IGNITION_PIN 36
// DIGITAL 2: ENGINE RELAYS
#define RELAY_1_PIN 23 // pin to disable ENGINE STOP
#define RELAY_2_PIN 25 // pin to enable REGULATION AND FUEL SOLENOID
#define RELAY_3_PIN 27 // pin to enable STARTER
#define RELAY_4_PIN 29

/* --- START ANALOG PINS --- */
// ANALOG 1: POTENTIOMETERS
#define ACTUATOR_CURRENT_PIN 0
#define MOTOR_CURRENT_PIN 1
#define BALLAST_SPEED_PIN 2
#define LOCK_CVT_PIN 3

/*********** VALUES ***********/
/* --- CONSTANTS --- */
#define KEYLENGTH 4
#define BAUD 9600
#define SHORTEST 100
#define SHORTER 300
#define SHORT 800
#define MEDIUM 1000
#define LONG 1500
#define LONGER 2000
#define LCD_WIDTH 20
#define LCD_HEIGHT 4

/* --- SERIAL COMMANDS --- */
#define LCD_I2C_PORT 0x3F
#define RFID_CARD 0x02
#define RFID_READ 0x03
#define RFID_WRITE 0x04

// MOTOR CONFIGURATIONS
#define MOTOR_LOW 25
#define MOTOR_MEDIUM 50
#define MOTOR_HIGH 100
#define ACTUATOR_LOW 25
#define ACTUATOR_MEDIUM 50
